from datetime import datetime
from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import LargeBinary
from ReStart.db_config import engine, Session
from ReStart.models import Base
from django.db.models.signals import post_migrate
from django.dispatch import receiver



def convert_to_dict(obj):
    return { c.name: getattr(obj, c.name) for c in obj.__table__.columns if c.name != 'official_regulations' }

def get_nullable_data(json_data, key, default):
    return json_data[key] if key in json_data else default

class Organization(Base):
    __tablename__ = 'organizations'
    __table_args__ = { 'extend_existing': True }

    id: Mapped[int] = mapped_column(primary_key=True)
    organization_id: Mapped[int] = mapped_column(nullable=False)
    name: Mapped[str] = mapped_column(String(256), nullable=True)
    students_grade_1: Mapped[int] = mapped_column(default=0, nullable=False)
    students_grade_2: Mapped[int] = mapped_column(default=0, nullable=False)
    students_grade_3: Mapped[int] = mapped_column(default=0, nullable=False)
    students_grade_4: Mapped[int] = mapped_column(default=0, nullable=False)
    students_grade_5: Mapped[int] = mapped_column(default=0, nullable=False)
    students_grade_6: Mapped[int] = mapped_column(default=0, nullable=False)
    students_grade_7: Mapped[int] = mapped_column(default=0, nullable=False)
    students_grade_8: Mapped[int] = mapped_column(default=0, nullable=False)
    students_grade_9: Mapped[int] = mapped_column(default=0, nullable=False)
    students_grade_10: Mapped[int] = mapped_column(default=0, nullable=False)
    students_grade_11: Mapped[int] = mapped_column(default=0, nullable=False)
    students_total: Mapped[int] = mapped_column(default=0, nullable=False)
    students_organization: Mapped[int] = mapped_column(default=0, nullable=False)
    creation_time: Mapped[datetime] = mapped_column(nullable=False)
    hours_mon: Mapped[int] = mapped_column(default=0, nullable=False)
    hours_tue: Mapped[int] = mapped_column(default=0, nullable=False)
    hours_wed: Mapped[int] = mapped_column(default=0, nullable=False)
    hours_thu: Mapped[int] = mapped_column(default=0, nullable=False)
    hours_fri: Mapped[int] = mapped_column(default=0, nullable=False)
    hours_sat: Mapped[int] = mapped_column(default=0, nullable=False)
    hours_sun: Mapped[int] = mapped_column(default=0, nullable=False)
    is_autogenerated: Mapped[bool] = mapped_column(default=True, nullable=False)
    achievements: Mapped[LargeBinary] = mapped_column(LargeBinary, default=None, nullable=True)

    def modify_from_dict(self, data):
        self.students_grade_1 = get_nullable_data(data, 'students_grade_1', self.students_grade_1)
        self.students_grade_2 = get_nullable_data(data, 'students_grade_2', self.students_grade_2)
        self.students_grade_3 = get_nullable_data(data, 'students_grade_3', self.students_grade_3)
        self.students_grade_4 = get_nullable_data(data, 'students_grade_4', self.students_grade_4)
        self.students_grade_5 = get_nullable_data(data, 'students_grade_5', self.students_grade_5)
        self.students_grade_6 = get_nullable_data(data, 'students_grade_6', self.students_grade_6)
        self.students_grade_7 = get_nullable_data(data, 'students_grade_7', self.students_grade_7)
        self.students_grade_8 = get_nullable_data(data, 'students_grade_8', self.students_grade_8)
        self.students_grade_9 = get_nullable_data(data, 'students_grade_9', self.students_grade_9)
        self.students_grade_10 = get_nullable_data(data, 'students_grade_10', self.students_grade_10)
        self.students_grade_11 = get_nullable_data(data, 'students_grade_11', self.students_grade_11)
        self.students_total = get_nullable_data(data, 'students_total', self.students_total)
        self.students_organization = get_nullable_data(data, 'students_organization', self.students_organization)
        self.hours_mon = get_nullable_data(data, 'hours_mon', self.hours_mon)
        self.hours_tue = get_nullable_data(data, 'hours_tue', self.hours_tue)
        self.hours_wed = get_nullable_data(data, 'hours_wed', self.hours_wed)
        self.hours_thu = get_nullable_data(data, 'hours_thu', self.hours_thu)
        self.hours_fri = get_nullable_data(data, 'hours_fri', self.hours_fri)
        self.hours_sat = get_nullable_data(data, 'hours_sat', self.hours_sat)
        self.hours_sun = get_nullable_data(data, 'hours_sun', self.hours_sun)
        self.achievements = get_nullable_data(data, 'achievements', self.achievements)

class Sports(Base):
    __tablename__ = 'sports'
    __table_args__ = { 'extend_existing': True }

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(64), default='-', nullable=False)
    student_count: Mapped[int] = mapped_column(default=0, nullable=False)
    # Привязка к версии отчета, Именно к Organization.id, не Organization.organization_id!
    organization_id: Mapped[int] = mapped_column(default=-1, nullable=False)

    def modify_from_dict(self, data):
        self.name = get_nullable_data(data, 'name', self.name)
        self.student_count = get_nullable_data(data, 'student_count', self.student_count)


class Event(Base):
    __tablename__ = 'events'
    __table_args__ = { 'extend_existing': True }

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(64), default='-', nullable=False)
    # Если is_official - то используется только это поле
    student_count_all: Mapped[int] = mapped_column(default=0, nullable=False)
    student_count_organization: Mapped[int] = mapped_column(default=0, nullable=False)
    # Привязка к системному id отчета, Именно к Organization.id, не Organization.organization_id!
    organization_id: Mapped[int] = mapped_column(default=-1, nullable=False)
    is_official: Mapped[bool] = mapped_column(default=False, nullable=False)
    official_type: Mapped[str] = mapped_column(String(64), default='-', nullable=False)
    official_location: Mapped[str] = mapped_column(String(64), default='-', nullable=False)
    official_organizer: Mapped[str] = mapped_column(String(64), default='-', nullable=False)
    official_regulations = mapped_column(LargeBinary, default=None, nullable=True)
    date: Mapped[datetime] = mapped_column(default=datetime(1970, 1, 1), nullable=False)
    
    def modify_from_dict(self, data):
        self.name = get_nullable_data(data, 'name', self.name)
        self.student_count_all = get_nullable_data(data, 'student_count_all', self.student_count_all)
        self.student_count_organization = get_nullable_data(data, 'student_count_organization', self.student_count_organization)
        self.is_official = get_nullable_data(data, 'is_official', self.is_official)
        self.official_type = get_nullable_data(data, 'official_type', self.official_type)
        self.official_location = get_nullable_data(data, 'official_location', self.official_location)
        self.official_organizer = get_nullable_data(data, 'official_organizer', self.official_organizer)
        self.official_regulations = get_nullable_data(data, 'official_regulations', self.official_regulations)
        self.date = get_nullable_data(data, 'date', self.date)

class CustomSports(Base):
    __tablename__ = 'custom_sports'
    __table_args__ = { 'extend_existing': True }

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(64), nullable=False)

class CustomEvent(Base):
    __tablename__ = 'custom_event'
    __table_args__ = { 'extend_existing': True }

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(64), nullable=False)
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)

Base.metadata.create_all(bind=engine)

@receiver(post_migrate)
def create_default_sports(sender, **kwargs):
    session = Session()
    DEFAULT_SPORTS = [
        'Баскетбол',
        'Бокс',
        'Волейбол',
        'Дартс',
        'Лыжные гонки',
        'Настольный теннис',
        'Самбо',
        'Легкая атлетика',
        'Шахматы',
        'Футбол'
    ]
    first_sports = session.query(CustomSports).filter(CustomSports.name==DEFAULT_SPORTS[0]).exists()
    if session.query(first_sports).scalar():
        return

    result = []
    for sports_name in DEFAULT_SPORTS:
        sports = CustomSports(name=sports_name)
        result.append(sports)

    print('Виды спорта добавлены')

    session.add_all(result)
    session.commit()